"""Answer parsing for the adjudication stage.

Input: the text generated by the model for one prompt. Output: the ``llm_dis_map``
contract, a string of the form ``G2Pxxxxx``, ``G2Pa;G2Pb`` or ``NO MATCH`` (``None`` when
no answer line could be parsed), plus the flags ``answer_format_valid``,
``answer_uncertain`` and ``answer_ids_in_candidates`` written next to it in the output
parquet. ``restrict_to_panel`` then keeps only the ids of the released panel.
"""
from __future__ import annotations

import re
from collections.abc import Iterable
from typing import Any

G2P_ID_RE = re.compile(r"G2P\d+")
NO_MATCH = "NO MATCH"


def extract_last_answer(text: str | None) -> str | None:
    """Return the text after the last ``ANSWER:`` marker up to the end of its line, or None.

    The last occurrence is taken because reasoning traces can quote the schema before the
    final line, and because GPT-OSS harmony output concatenates the analysis and final
    channels as ``...assistantfinalANSWER: ...``. The marker match is case-insensitive.
    """
    # Locate every marker first; a greedy match would swallow a later marker on the same line.
    marks = list(re.finditer(r"ANSWER:\s*", text or "", flags=re.IGNORECASE))
    if not marks:
        return None
    return (text[marks[-1].end():].split("\n", 1)[0]).strip()


def parse_answer(raw_answer: str | None, allowed_ids: Iterable[str | None] | None = None) -> dict[str, Any]:
    """Normalise the text after ``ANSWER:`` into the ``llm_dis_map`` contract.

    Returns a dict with:
      llm_dis_map            "G2Pxxxxx", "G2Pa;G2Pb", "NO MATCH", or None (no parseable answer)
      answer_format_valid    True when the answer is exactly the schema (ids ; ids, NO MATCH)
      answer_uncertain       True when the model said UNCERTAIN (mapped to NO MATCH)
      answer_ids_in_candidates
                             True when every returned id is one of the offered candidates
                             (None when there are no ids or no candidate list was given)

    Ids are extracted with ``G2P\\d+`` so decorations ("G2P01236 (EFTUD2)", markdown, a
    trailing full stop) still yield the id, with ``answer_format_valid`` False. Ids outside
    the candidate list are flagged, not removed; ``final_data_clean.py`` drops them.
    """
    out: dict[str, Any] = {
        "llm_dis_map": None,
        "answer_format_valid": False,
        "answer_uncertain": False,
        "answer_ids_in_candidates": None,
    }
    if raw_answer is None:
        return out
    text = str(raw_answer).strip().strip("`*\"' ").rstrip(".").strip()
    upper = text.upper()
    if "UNCERTAIN" in upper and not G2P_ID_RE.search(text):
        out.update(llm_dis_map=NO_MATCH, answer_uncertain=True,
                   answer_format_valid=upper == "UNCERTAIN")
        return out
    if "NO MATCH" in upper and not G2P_ID_RE.search(text):
        out.update(llm_dis_map=NO_MATCH, answer_format_valid=upper == NO_MATCH)
        return out
    ids: list[str] = []
    for m in G2P_ID_RE.findall(text):
        if m not in ids:
            ids.append(m)
    if not ids:
        return out
    out["llm_dis_map"] = ";".join(ids)
    out["answer_format_valid"] = re.fullmatch(r"G2P\d+(\s*;\s*G2P\d+)*", text) is not None
    if allowed_ids is not None:
        allowed = {a for a in allowed_ids if a}
        out["answer_ids_in_candidates"] = all(i in allowed for i in ids)
    return out


def restrict_to_panel(dis_map: str | None, final_ids: set[str] | None) -> str | None:
    """Keep only ids of the released panel; an answer left empty becomes NO MATCH.

    ``final_ids=None`` disables the restriction; ``None`` and ``NO MATCH`` pass through.
    """
    if final_ids is None or dis_map in (None, NO_MATCH):
        return dis_map
    kept = [i for i in str(dis_map).split(";") if i in final_ids]
    return ";".join(kept) if kept else NO_MATCH
